### ISSUE TITLE
Sign and verify message using terra

### ISSUE THREAD

**Issue by poojachigitey** [terra-money/terra.js#104]
Hi, I am unable to use custom sign for terra station signing. can anybody help about this.

**Comment by hanjukim** [comment]
What do you mean by `terra station signing`. I need a context and some more details to help you out.

**Comment by tkowalczyk** [comment]
We are also working on this:
https://github.com/terra-money/terra.js/issues/95
https://github.com/terra-money/wallet-provider/issues/4
