### ISSUE TITLE
Execute wasm contract failed when using extension

### ISSUE THREAD

**Issue by ingbond** [terra-money/terra.js#109]
When I try to executing contract using Extension, I'm got an error: "rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: Error parsing into type contract::msg::HandleMsg: unknown variant `eyJhZGRfcGxheWVyIjp7fX0=`, expected `add_user`: execute wasm contract failed: invalid request".
What's the correct way of using the extension?
Code:
`
this.client = new LocalTerra();
this.extension = new Extension();
this.extension.connect();
this.extension.on("onConnect", (w: Wallet) => {
      this.wallet = w;
});

const execute = new MsgExecuteContract(
    this.wallet.address, // sender
    "terra1tndcaqxkpc5ce9qee5ggqf430mr2z3pefe5wj6", // contract account address
    { add_user: {} }, // handle msg
    { uluna: 100000} // coins
);

this.extension.post({
    msgs: [execute],
});

this.extension.once("onPost", async (data: any) => {
    console.log("post", data);
});
`

**Comment by hanjukim** [comment]
The latest terra.js and LocalTerra is compatible with bombay network

**Comment by bond-igor** [comment]
@hanjukim could you please clarify, what should I do, if I need to test the contract execution with the extension on my local machine before I go to the Testnet?
