### ISSUE TITLE
window.isTerraExtensionAvailable is true but ext do not open

### ISSUE THREAD

**Issue by AndonMitev** [terra-money/terra.js#110]
I'm trying to inject a wallet in terra dapps and i have debugged the wallet provider from where i check is looking for prop in window which is isTerraExtensionAvailable, I have mine setted to true but still my wallet is not recognized from the dapps any suggestions on that? Thanks in advance!

**Comment by hanjukim** [comment]
If you are using https://github.com/terra-money/wallet-provider could you post this issue there?

**Comment by AndonMitev** [comment]
So basically i'm using Liquality Wallet and I'm trying to inject it in terra dapps
