### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by cn-80** [terra-money/terra.js#123]
Trying to use this code to connect to the extension:

```javascript
const terraExtension = new Terra.Extension();
terraExtension.connect();
terraExtension.on("connect", (wallet) => {
  console.log(wallet);
});
```

The first time I ran it, Station wallet showed up and asked me to connect and I did.

However, on subsequent runs,  I'm seeing these two errors:

![readable-process](https://user-images.githubusercontent.com/84057174/130322413-1c8381c6-dea8-4fa4-b440-31804279bc8e.png)
![writable-error](https://user-images.githubusercontent.com/84057174/130322414-0c44927d-3062-4ec0-ab71-6690761ae12e.png)

**Comment by y-pakorn** [comment]
I'm getting these errors as well! Any updates?
