### ISSUE TITLE
signing MsgExecuteContract failing

### ISSUE THREAD

**Issue by czelios** [terra-money/terra.js#132]
Hi!

I detected an error while signing transaction. Here is sample code to ilustrate the issue:

```
  const wallet = terra.wallet(mk);
  const singInKYCVault = new MsgExecuteContract(
    wallet.key.accAddress,
    config.terra.kycVaultContract,
    {
      "register_address":
        {
            "address": "terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v"
        }
    }
  )
  

  const signedTxs2 = await wallet
    .createAndSignTx({
      msgs: [singInKYCVault],
    });
```

While running wallet.createAndSignTx i get this error: 'json: cannot unmarshal object into Go value of type string'.
Testing on version 2.0.5
For exapmle the same code is working properly on version 1.8.5

**Comment by YunSuk-Yeo** [comment]
Which network are you using now?? If you want to use Mainnet or Tequila network, please use v1.x.x terra.js

v2.x.x is for bombay and Columbus-5 upgrade

**Comment by czelios** [comment]
I am using columbus-4 both mainnet and testnet. Thank you for clarification :)
