### ISSUE TITLE
query and Binary data?

### ISSUE THREAD

**Issue by dakom** [terra-money/terra.js#133]
(still getting my feet wet - apologies if I missed something)

1. The CosmWasm docs and examples show that it's allowed for a contract to return `Binary` data. However, I don't see this when I look in the TxLogs ... is there a different way of getting this data via Terra.JS? I do see attributes...

2. Similarly, the CosmWasm docs show a separate ability for Query messages. I don't see this in Terra.JS

**Comment by dakom** [comment]
oh I see query is on the `.wasm` module... but binary data?

**Comment by dakom** [comment]
Sorry - let me clarify. For Queries it all works fine - contract returns binary data and it shows up as JSON on the client side.

However, for Execute, I call `set_data` on the contract but I do not see it in the transaction logs

**Comment by hanjukim** [comment]
It's could not be fully compatible because we integrated CosmWasm in very early stage.
