### ISSUE TITLE
WebSocketClient does not connect

### ISSUE THREAD

**Issue by Green7** [terra-money/terra.js#145]
After updating to version 2.0.14 I cannot connect via WebSocketClient.

I checked the cause of the problem:
- the WebSocketClient `start()` function is not called. Previously, it was called at the end of `subscribe()`
So this should be corrected, or the start() function should be made public.

**Comment by Vritra4** [comment]
fix: https://github.com/terra-money/terra.js/commit/998fdfbaabee7d81176d3d2bb377ea0a5dfb61d0
