### ISSUE TITLE
Can i retrieve mAsset and farming data of specific address with this module?

### ISSUE THREAD

**Issue by liftingturn** [terra-money/terra.js#146]
Is it valid? 
As i tested 
```
 await terra.bank.balance(targetWalletAddress);
 ```
 it only shows the coin assets. except mAsset and Lps

**Comment by Green7** [comment]
To get token balance you need query token contract. 
Something like: 
` await lcdClient.wasm.contractQuery(contractAddress, { balance: { address: your_wallet_address } }) `

**Comment by liftingturn** [comment]
thanks, 
For now, it seems there's no api that retrieves whole balance (include tokens) of terra wallet. right?

**Comment by Green7** [comment]
You're right. The tokens are "decentralized", so there is no single api to get the balance of all tokens.

**Comment by dyustc** [comment]
> To get token balance you need query token contract. Something like: `await lcdClient.wasm.contractQuery(contractAddress, { balance: { address: your_wallet_address } })`

Hi, I have a question. If I only need to query for all the balance in the wallet, like the coins and tokens in Terra Finder, is there a API to retrieve all the balances?

**Comment by mr-rooftop** [comment]
> 

I guess not.
If you get e.g. a very new token in your wallet, it will also not be shown on terra station until you add the token address.

But you can make a list of all popular tokens, and then just run the `contractQuery()` function in a loop.

Perhaps you can also query all tokens that got instantiated by the CW-20 base contract, but not sure if/how that's possible. Also you would then have many tokens that devs deployed just for fun.

**Comment by o-az** [comment]
> @dyustc
> 
> I guess not. If you get e.g. a very new token in your wallet, it will also not be shown on terra station until you add the token address.
> 
> But you can make a list of all popular tokens, and then just run the `contractQuery()` function in a loop.
> 
> Perhaps you can also query all tokens that got instantiated by the CW-20 base contract, but not sure if/how that's possible. Also you would then have many tokens that devs deployed just for fun.

is there an RPC / REST / GraphQL endpoint we can send `contractQuery` to without having to download `terra.js` or any external libraries?

**Comment by mr-rooftop** [comment]
absolutely: https://lcd.terra.dev/swagger/#/Query/ContractStore

**Comment by o-az** [comment]
> absolutely: https://lcd.terra.dev/swagger/#/Query/ContractStore

Thank you. I ended up hitting the mantle endpoint and passing a graphQL query. This way I'm able to pass multiple contract queries in one call. 

Two things I'm curious about:

- does this endpoint that you share retrieve data from the same endpoint as https://mantle.terra.dev/ ?

- what's the difference between lcd.terra.dev and fcd.terra.dev ?
