### ISSUE TITLE
txInfo from col-4

### ISSUE THREAD

**Issue by czelios** [terra-money/terra.js#149]
Hi!

I have a problem calling txInfo for transaction made in col-4. I am getting 404 not found error while in terra finder it works like a charm.
Here is an example call:
await terra.tx.txInfo('D7BC896AAF3168DC44A2F2F30E47BD9DCB0ADDDB71F74EAFDAC49752205444C4')

terra is in this case LCDClient initialised with col-5

Could you please check this scenario?

**Comment by shlomokraus** [comment]
+1

**Comment by Vritra4** [comment]
not available with LCD. LCDs have data from genesis of col-5 only.
