### ISSUE TITLE
`exchangeRate` does not return prices in the requested denomination

### ISSUE THREAD

**Issue by harryscholes** [terra-money/terra.js#157]
The `exchangeRate` docstring says:

https://github.com/terra-money/terra.js/blob/1c7b37b8c3e540b1ff7d777d4a334ad7f3ea2837/src/client/lcd/api/OracleAPI.ts#L83-L87

But `terra.oracle.exchangeRate("uusd")` returns `43.114990898875845`, i.e. the price in USD, not uusd

**Comment by harryscholes** [comment]
@Vritra4 why did you close the issue? It hasn't been fixed yet

**Comment by Vritra4** [comment]
oh sorry i misread this issue :(
