### ISSUE TITLE
multiSend, wrong number of signers; expected 3, got 1: unauthorized: invalid request

### ISSUE THREAD

**Issue by locoy** [terra-money/terra.js#159]
https://github.com/terra-money/terra.js/wiki/MultiSend

all the example code, get the result of rpc error: code = InvalidArgument desc = wrong number of signers; expected 3, got 1: unauthorized: invalid request

the problem function is:

  const tx = await wallet.createTx({
    msgs: [
      new MsgMultiSend(
        [
          new MsgMultiSend.Input(keys.test1.accAddress, "1000000uluna"),
          new MsgMultiSend.Input(keys.test2.accAddress, "1000000uluna"),
          new MsgMultiSend.Input(keys.test3.accAddress, "1000000uluna"),
        ],
        [output, output, output]
      ),
    ],
  });

**Comment by dagogodboss** [comment]
Has this been resolved

**Comment by Vritra4** [comment]
sorry to late response. terra.js 3.0 is out now and there's a lot of changes. please try like this. [sendMultisend.ts](https://github.com/terra-money/terra.js/blob/main/integration-tests/sendMultisend.ts)
please reopen this issue if you need :)
