### ISSUE TITLE
can not custom set the fee item for tx

### ISSUE THREAD

**Issue by kelvv** [terra-money/terra.js#160]
const fee = new StdFee(800000, { uluna: '100000' })

  const sign = await wallet.createAndSignTx({
    msgs: [send],
    fee
  }).catch(err => {
    console.log(err.response.data.error)
  })

I can not success post this swap to the terra blockchain，I god timeout error，How can I custom set the fee for the trading? thank you

**Comment by Vritra4** [comment]
timeout error is not related to fee. reopen it if you are still having this problem. :)
and terra.js 3.0 is out now. please use it.
