### ISSUE TITLE
Sometimes apear <account sequence mismatch> 

### ISSUE THREAD

**Issue by OlegDO** [terra-money/terra.js#168]
After relocate on bombay-12 I began to get this error sometimes. 
Same code as my, but from example, only data of wallet and amount, denoms and etc changes.

 ``` const tx = await wallet.createTx({
    msgs: [
      new MsgMultiSend(
        [
          new MsgMultiSend.Input(keys.test1.accAddress, "1000000uluna"),
          new MsgMultiSend.Input(keys.test2.accAddress, "1000000uluna"),
          new MsgMultiSend.Input(keys.test3.accAddress, "1000000uluna"),
        ],
        [output, output, output]
      ),
    ],
  });

  const signatures = await Promise.all(
    ["test1", "test2", "test3"].map(async (keyName) => {
      const key = keys[keyName] as MnemonicKey;
      const acc = (await client.auth.accountInfo(key.accAddress)) as Account;

      tx.account_number = acc.account_number;
      tx.sequence = acc.sequence;

      return key.createSignature(tx);
    })
  );

  const stdTx = new StdTx(tx.msgs, tx.fee, signatures, tx.memo);

  await client.tx
    .broadcastSync(stdTx)
    .then((result) => {
      console.log(result);
    })
    .catch((err) => {
      console.error(err.message);
    });
} ```

Full error message: rpc error: InvalidArgument desc = account sequence mismatch, expected 161, got 160: incorrect account sequence: invalid request

**Comment by dagogodboss** [comment]
Can you drop the code that produce this error

**Comment by bvs-work** [comment]
I have the similar error I guess. It arises spontaneously, and there is no pattern. This was not the case on `tequila` This only happens on `bombay` and quite often
```
const msg = new MsgSend(accAddress, self.receiverTerraWallet, amount)
        const tx = yield self.terraClient.wallet.createAndSignTx({
          msgs: [msg],
          memo: self.for,
        })
const txResult = yield self.terraClient.terra.tx.broadcast(tx)
```
after the broadcast I sometimes get `signature verification failed: please verify account number (69745) sequence (97) and chain-id (bombay-12) unauthorized`

**Comment by OlegDO** [comment]
@dagogodboss All works fine, but sometimes this error appear in random moments.

const tx = await wallet.createTx({
      msgs: [new MsgMultiSend(_msgs, [...multiSendOutoutData])],
      feeDenoms: ['uusd'],
      gasPrices: '0.15uusd',
    });
    
    const signatures = await Promise.all(
      ['im', 'spare'].map(async keyName => {
        const key = keys[keyName];
        const acc = await client.auth.accountInfo(key.accAddress);

        tx.account_number = acc.account_number;
        tx.sequence = acc.sequence;

        return key.createSignature(tx);
      })
    );

    const stdTx = new StdTx(tx.msgs, tx.fee, signatures, tx.memo);

    const response = await client.tx
      .broadcastSync(stdTx)
      .then(result => {
        return { result };
      })
      .catch(error => {
        return { error };
      });

**Comment by hanjukim** [comment]
The Guideline for solving sequence mismatch problem:

1. Use one node for broadcasting the tx. Do not use public infrastructure because it has load balancer before the cluster
2. Save sequence in local variable and use it for making sequential transactions within a block.
