### ISSUE TITLE
Links to documentation of querying functions of `LCDClient` are outdated and returning 404 

### ISSUE THREAD

**Issue by jaworek** [terra-money/terra.js#173]
Links to documentation of querying functions of `LCDClient` seems to be outdated and not working anymore.
https://github.com/terra-money/terra.js/wiki/Querying

While digging through documentation, I was able to find their documentation here:
https://terra-money.github.io/terra.js/classes/LCDClient.html#wasm

It seems that there's no option to submit a PR to fix those issues myself, so I'm leaving this info for person who has editing rights to that part of the project.

**Comment by Vritra4** [comment]
tested quering functions and works fine.
please reopen this issue if you have still have a problem.
