### ISSUE TITLE
Documentation for errors returned while querying Terra using `LCDClient`

### ISSUE THREAD

**Issue by jaworek** [terra-money/terra.js#174]
I'm looking for documentation of errors that are returned from `LCDClient` when querying Terra blockchain.
It would be useful to have a list of errors with their error codes and messages.
This would allow parsing these errors and displaying messages that are more understandable to end user.

E.g. Instead of "0uusd is smaller than 550000uusd:insufficient funds:insufficient funds", it could be displayed to users as "Insufficient funds. You need to have UST in your wallet to cover transaction fees."

Currently to achieve this it requires either checking manually each error code or catching error using `error.includes("insufficient funds")` and then displaying other message to the user. Second solution might be easily breakable when message returned by blockchain changes in the future.

**Comment by hanjukim** [comment]
The actual error messages are coming from Terra Core, and we are in development for parsing errors in human readable form, and it will be released soon..
