### ISSUE TITLE
one transaction with multi execution

### ISSUE THREAD

**Issue by ChunHuCui** [terra-money/terra.js#176]
Hi. Development team.
I'd like to send multi messages to the different smart contracts in one transaction.
it means the source contract address is one, the destination contract addresses aren't the same, and the messages per destination address are different too.
I checked the MsgExecuteContract function, but I can't find the resolution.
is there any way to implement this?

Thank you in advance.

**Comment by Vritra4** [comment]
MsgExecuteContract is a message and multiple messages can be included in a transaction.
so you could set multiple messages in CreateTxOptions.msgs[] and sign/broadcast it. :)

**Comment by ChunHuCui** [comment]
thank you @Vritra4. it's working well.
