### ISSUE TITLE
Module `@terra-money/terra.js` has no exported member `StdFee`

### ISSUE THREAD

**Issue by 0xBlockchain** [terra-money/terra.js#182]
Getting type error `Module '"@terra-money/terra.js"' has no exported member 'StdFee'.` with terra.js v3
![Screen Shot 2021-12-01 at 9 47 45 AM](https://user-images.githubusercontent.com/33234035/144255936-0328f3ae-6262-422d-8ee9-5bb52a3efd8e.png)

**Comment by Vritra4** [comment]
StdFee is removed. use Fee instead of StdFee
