### ISSUE TITLE
signature verification failed; please verify account number (0) and chain-id (): unauthorized

### ISSUE THREAD

**Issue by OlegDO** [terra-money/terra.js#187]
Hi, we have worked code yesterday, that's transeer money between accounts. Today on each payment in mobile app, web we got 
error: 
```signature verification failed; please verify account number (0) and chain-id (): unauthorized```
This happens when we check broadcasted tx with the func (isTxError).
But in picture 1, you can see that we got correct account_number and sequence.
On picture 2 you can see object of a error.
1) ![image](https://user-images.githubusercontent.com/44732463/146151285-a38a7783-8d06-4a13-bb94-64b54733c5f4.png)
2) ![image](https://user-images.githubusercontent.com/44732463/146151337-83e23490-1c5f-4cfa-a97a-f22cb8c01b40.png)

**Comment by Vritra4** [comment]
Our testnet is under maintenance. retry it later.

**Comment by Vritra4** [comment]
bombay testnet is working fine so i think it is resolved.
please reopen it if you are still suffered.
