### ISSUE TITLE
use https://lcd.terra.dev/ And columbus-5 to obtain transaction data, and the error is as follows:

### ISSUE THREAD

**Issue by coder-chenda** [terra-money/terra.js#192]
![image](https://user-images.githubusercontent.com/83049018/147057841-986ed225-87c2-4e6e-9727-f092e4c40bba.png)

**Comment by coder-chenda** [comment]
Can you help me see why?

**Comment by coder-chenda** [comment]
Is this related to the node version? I tried V14 17.14 and V14 16.1 you can't even try

**Comment by Vritra4** [comment]
still having this problem?

**Comment by coder-chenda** [comment]
> 仍然有这个问题？
This problem has always existed. Haven't you met it?
