### ISSUE TITLE
Is it possible to do staking in terra.js?

### ISSUE THREAD

**Issue by btfdip** [terra-money/terra.js#195]
1). All I know is we can do staking by terrad: https://docs.terra.money/Reference/terrad/subcommands.html#tx-staking-delegate

2). current terra.js can only **query** the staking information:

https://terra-money.github.io/terra.js/classes/StakingAPI.html

**Comment by Vritra4** [comment]
you can use MsgDelegate. create, sign, and broadcast a Tx with MsgDelegate.
