### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '@type'), when using await wallet.accountNumber()

### ISSUE THREAD

**Issue by btfdip** [terra-money/terra.js#197]
When I try to output 
> console.log(await wallet.accountNumber());

It just showed me the following bug.

![image](https://user-images.githubusercontent.com/96004784/147555142-aa1bb8e1-7249-4933-8784-7fe66bd1b2ef.png)

- There is not error on dev-env: https://bombay-lcd.terra.dev, bombay-12.

- But when I change to a private node from quicknode(with chainid columbus-5),  the error appeared as above.

The client info showed in quicknode is as follows:

![image](https://user-images.githubusercontent.com/96004784/147555414-ab1b5baf-9a5b-45e4-a247-92f7b2fd64c6.png)

Any hint?

**Comment by Vritra4** [comment]
Which version are you using?

**Comment by btfdip** [comment]
Thanks for your hint, my version is 2.1.23, I changed it to 2.0.0, it works now. hope this can help someone else.

**Comment by Vritra4** [comment]
@btfdip our latest version of terra.js is 3.0.2. i don’t recommend you to use 2.0.x :)

**Comment by btfdip** [comment]
Interestingly, If I use 3.0.2, the problem still exists, 

so I should contact quicknode to suggest them to update their server client??

**Comment by Vritra4** [comment]
@btfdip could you try your quicknode instance with `terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v`?
it's one of our test account.
