### ISSUE TITLE
Description for "Making connection", not working in browser?

### ISSUE THREAD

**Issue by junosha** [terra-money/terra.js#198]
The Docs state this would work via node.js and in browser. Can someone point me in the right direction why this here is not working?

```
import Head from 'next/head'
import Layout, { siteTitle } from '../components/layout'
import utilStyles from '../styles/utils.module.css'

import { LCDClient, Coin } from '@terra-money/terra.js';

// connect to bombay testnet
const terra = new LCDClient({
  URL: 'https://bombay-lcd.terra.dev',
  chainID: 'bombay-12',
});
```
I get this error when I "npm run dev":

```
Module not found: Can't resolve '@terra-money/terra.js'
  3 | import utilStyles from '../styles/utils.module.css'
  4 | 
> 5 | import { LCDClient, Coin } from '@terra-money/terra.js';
  6 | 
  7 | // connect to bombay testnet
  8 | const terra = new LCDClient({
```

**Comment by Vritra4** [comment]
did you install terra.js with --save option?

**Comment by junosha** [comment]
yes I did

**Comment by Vritra4** [comment]
please see templates and quick starts in https://github.com/terra-money/wallet-provider

**Comment by junosha** [comment]
I tried to solve the issue that way and found different import commands there. They point to a js-file (wallet-provider.js) that is not included in the version of terra.js I get with `"npm install --save @terra-money/terra.js"
`
The imports in the next.js template are:
```
import { useWallet, WalletStatus } from '@terra-money/wallet-provider';
import { useConnectedWallet, useLCDClient } from '@terra-money/wallet-provider';
```
While in the docs it is:
`import { LCDClient, Coin } from '@terra-money/terra.js';`
... the import just points to the folder (in which there is no file named wallet-provider.js). It is strange because it works when run on the server side with node.js.

**Comment by hanjukim** [comment]
@iamssen Is there still a problem with terra.js version compatiability?
