### ISSUE TITLE
Hello! Where can I find an example of terra.js manually signing a transaction? Can I provide a link to trouble?

### ISSUE THREAD

**Issue by chaim-g** [terra-money/terra.js#199]

**Comment by chaim-g** [comment]
I just want to simply send luna through terra.js

**Comment by Vritra4** [comment]
https://github.com/terra-money/terra.js/blob/308fb8086d46ed898f374a7a575a71c30d35e8b0/integration-tests/send.ts

**Comment by chaim-g** [comment]
I have seen this, I want to send it without using the wallet

**Comment by Vritra4** [comment]
what do you mean 'without using the wallet'?

**Comment by chaim-g** [comment]
https://terra-money.github.io/terra.py/guides/transactions.html#signing-transactions-manually
Js version like this

**Comment by Vritra4** [comment]
may i ask why do you need that? wallet is just combination of LCDClient and key.
https://github.com/terra-money/terra.js/blob/main/integration-tests/sendMultisend.ts can be an example anyway.
use MsgSend instead of MsgMultiSend, and createSignature instead of createSignaureAmino.

**Comment by chaim-g** [comment]
I’ll try it. I’m sorry it might be complicated. Thank you very much for your patient answer.

**Comment by Vritra4** [comment]
no problem :) then i'll close this issue. feel free to reopen this one or create new issue.
