### ISSUE TITLE
React Native: error on wallet.createAndSignTx

### ISSUE THREAD

**Issue by xcsob** [terra-money/terra.js#205]
Hello, 
I'm having hard time making a transaction on a React Native Application. 

I tried the same code on a javascript script and it works. Once I try this on a React Native Application, it breaks. 
The only difference between the two scrips is that I'm using the react-native-mnemonic-key for the React Native app, while on the js script I use the MnemonicKey object from terra-js library. 

I tried to make the MnemonicKey object work, but I couldn't so I switched for the other library. 

This is my package.json dependencies: 

"dependencies": {
    "@anchor-protocol/anchor-earn": "^2.0.0-alpha1",
    "@expo/vector-icons": "^12.0.5",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@terra-money/terra.js": "^3.0.0",
    "buffer": "^6.0.3",
    "events": "^3.3.0",
    "expo": "~43.0.2",
    "expo-secure-store": "^11.0.3",
    "expo-splash-screen": "~0.13.5",
    "expo-status-bar": "~1.1.0",
    "expo-updates": "~0.10.13",
    "firebase": "^9.6.1",
    "lodash": "^4.17.21",
    "mobx": "^6.3.8",
    "mobx-react": "^7.2.1",
    "node-libs-react-native": "^1.2.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-native": "^0.66.0",
    "react-native-android-open-settings": "^1.3.0",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-camera": "^4.2.1",
    "react-native-confetti-cannon": "^1.5.2",
    "react-native-curved-bottom-bar": "^1.7.0",
    "react-native-device-info": "^8.4.8",
    "react-native-elements": "^3.4.2",
    "react-native-floating-action": "^1.22.0",
    "react-native-gesture-handler": "^2.1.0",
    "react-native-get-random-values": "^1.7.1",
    "react-native-material-ripple": "^0.9.1",
    "react-native-mnemonic-key": "^0.1.3",
    "react-native-modal": "^12.0.0",
    "react-native-pager-view": "^5.4.9",
    "react-native-platform-touchable": "^1.1.1",
    "react-native-reanimated": "^2.3.0-alpha.2",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-svg": "^12.1.1",
    "react-native-vector-icons": "^9.0.0",
    "react-native-web": "0.17.1",
    "stream": "^0.0.2",
    "svgs": "^4.2.0"
  }

This is the code that generates the problem:  

  `
const terra = new LCDClient({
            URL: 'https://bombay-lcd.terra.dev',
            chainID: 'bombay-12',
        });
        const mk = await RNMnemonicKey.create({ mnemonic: phrase })
        const wallet = terra.wallet(mk);

        // create a simple message that moves coin balances
        const send = new MsgSend(
            wallet.key.accAddress,
            _to,
            { uusd: 1000 }
        );

        const tx = await wallet.createAndSignTx({
            msgs: [send],
            memo: "Hello"
        });

        console.log(tx)

        const txResult = await terra.tx.broadcast(tx);

        console.log(txResult)
`

The error (warning) that I get is the following: 
`TypeError: public_key.packAny is not a function TypeError: public_key.packAny is not a function at SignerInfo.toProto (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appname:264871:87) at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appname:264817:23 at Array.map (<anonymous>) at AuthInfo.toProto (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appname:264816:40) at Tx.toProto (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appname:264678:34) at Tx.toBytes (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appname:264686:34) at TxAPI.encode (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appname:320402:29) at TxAPI.<anonymous> (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appname:320368:32) at step (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appname:320140:21) at Object.next (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appname:320070:16)`

**Comment by Vritra4** [comment]
react-native-mnemonic-key seems outdated. i'll see what i can do.

**Comment by xcsob** [comment]
> react-native-mnemonic-key seems outdated. i'll see what i can do.

What should I use then?
On Terra.js Readme there is written that the Mnemonic Key object of Terra js gives error when called and this is true.

I also installed the same version as Terra station, but it still generate errors.

**Comment by Vritra4** [comment]
i think you can just use MnemonicKey(from terra.js) for your react native app.

**Comment by xcsob** [comment]
> i think you can just use MnemonicKey(from terra.js^3.0.3) for your react native app.

Unfortunately, that's not the case. 
I tried using the terra.js^3.0.3 and substituting the line: 

`const mk = await RNMnemonicKey.create({ mnemonic: phrase })
`

with the line: 

`const mk = new MnemonicKey({ mnemonic: phrase })
`

and this is the error that I get: 

`TypeError: Cannot read properties of undefined (reading 'call') TypeError: Cannot read properties of undefined (reading 'call') at Hmac.CipherBase (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appName:282913:15) at new Hmac (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appName:283215:10) at createHmac (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appName:283269:12) at Object.hmacSHA512 (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appName:278265:12) at Object.fromSeed (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appName:278233:20) at MnemonicKey (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appName:277879:29) at sendToken$ (http://localhost:8081/src/services/blockchain/Terra/TerraBlockchainService.bundle?platform=ios&modulesOnly=true&app=com.appName&dev=true&minify=false&runModule=true&shallow=true:79:74) at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appName:24594:19) at Generator.invoke [as _invoke] (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appName:24764:24) at Generator.next (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.appName:24636:23)`

**Comment by Vritra4** [comment]
is cipher-base in your package-lock.json?

**Comment by xcsob** [comment]
> is cipher-base in your package-lock.json?

I didn't have it, but I added it to my package.json but nothing changed. 

The version I added is: 
`        "cipher-base": "^1.0.4",
`

**Comment by Vritra4** [comment]
not in package-lock.json? it means modules are not installed properly i guess. 
could you clear installed modules and install it again?

**Comment by Vritra4** [comment]
i don't know about react native but i think you can refer to https://github.com/terra-money/station-mobile
it is a react-native app and uses MnemonicKey from terra.js

**Comment by xcsob** [comment]
> i don't know about react native but i think you can refer to https://github.com/terra-money/station-mobile it is a react-native app and uses MnemonicKey from terra.js

Thanks. 
I already looked at the repository and it's trye

> not in package-lock.json? it means modules are not installed properly i guess. could you clear installed modules and install it again?

Yes, it is also in package-lock.json. I deleted the node modules library and install again. 


I already looked at the terra station mobile app, and it use mnemonic key from terra.js. I installed the same exact version of React Native and terra.js modules, but I still get the error. At this point, I don't know how to solve this honestly.

**Comment by hanjukim** [comment]
`react-native-mnemonic-key` is now archived.

**Comment by xcsob** [comment]
> `react-native-mnemonic-key` is now archived.

Thank you for advising me this. On the terra.js documentation there is still written that the library that should be used on react-native is this one. 
However, using the MnemonicKey from terra.js leads me to the error reported at [this comment](https://github.com/terra-money/terra.js/issues/205#issuecomment-1006456610). 
Do you know how to solve this?
