### ISSUE TITLE
Uncaught ReferenceError: process is not defined when using in web browser

### ISSUE THREAD

**Issue by y-pakorn** [terra-money/terra.js#206]
When I include this to `index.html` and ran the code below, `process is not defined` error got thrown.

I am developing plugin on the other language (Dart/Flutter) that utilize in-page `terra.js` module for functionality. If `Extension` can not be used then the functionality of using Terra station wallet will be disabled.

```html
<script
  crossorigin
  src="https://unpkg.com/@terra-money/terra.js/dist/bundle.js"
></script>
```
```js
ext = new Terra.Extension();
ext.connect();
```
![Screen Shot 2565-01-06 at 14 47 31](https://user-images.githubusercontent.com/48324733/148347668-bc811a99-60e5-49aa-9e16-3435c7a33252.png)

**Comment by hanjukim** [comment]
Fixed in #207
