### ISSUE TITLE
max_subscriptions_per_client 5 reached

### ISSUE THREAD

**Issue by OlegDO** [terra-money/terra.js#209]
```Request: msgInstantiateContract. All worked fine but today we get that error on instantiate that appear in random order.```
![image](https://user-images.githubusercontent.com/44732463/149099335-d0fadd6b-e035-421f-8bd2-ea7d787c1b6e.png)
```Response:```
![telegram-cloud-photo-size-2-5399820553583442179-y](https://user-images.githubusercontent.com/44732463/149098948-6629efbe-9bfa-40da-be91-3d0de27dc687.jpg)

**Comment by Vritra4** [comment]
it is a tendermint thing.. not from terra.js. 
i guess.. too many simultaneous request may causes this.

**Comment by modernlearner** [comment]
I have run into this issue as well. It occurred when I had multiple transactions being broadcast, when transactions were being broadcast simultaneously rather than in a synchronous fashion.
