### ISSUE TITLE
Default fee seems to be changed from uusd to uluna

### ISSUE THREAD

**Issue by laine-ust** [terra-money/terra.js#211]
It would seem that one the latest updates to terra.js has changed the default fee from `uusd` to `uluna`.

We're seeing many "complaints" / error reports about this on the Pylon telegram where I'm co-admin (because people don't have LUNA in their wallet), and some chatter in TG dev groups.

I think it might have happened with this commit, but I'm not entirely sure, since I'm pretty new to this stack
https://github.com/terra-money/terra.js/commit/7025f88714209a2acbc35110a13d86aab3403943

Please and thank you :)

**Comment by Vritra4** [comment]
defaule fee denom before the commit is uluna.. see [this](https://github.com/terra-money/terra.js/blob/7025f88714209a2acbc35110a13d86aab3403943/src/client/lcd/api/TxAPI.ts#L282).

**Comment by Vritra4** [comment]
@laine-ust could you check feeDenoms for createAndSignTx() and gasPrices for new LCDClient()?

**Comment by laine-ust** [comment]
@Vritra4 good point - i've been testing all the way back to `v2.0.5` and the default gasFee is `uluna` on `new LCDClient()`.

It might be unrelated then - sorry for the "noise".
