### ISSUE TITLE
Swapping from CW10 token to native token.

### ISSUE THREAD

**Issue by CartoshiN** [terra-money/terra.js#215]
Hi,

I'm trying to swap the bLuna CW20 token to the native asset UST using TerraSwap. I'm trying to swap the total amount of bLuna in my wallet. 

I'm able to get information about the UST>bLuna pool using:
```
const pool = "terra1qpd9n7afwf45rkjlpujrrdfh83pldec8rpujgn";
// Fetch the number of each asset in the pool.
const { assets } = await terra.wasm.contractQuery(pool, { pool: {} });
// Calculate belief price using pool balances.
const beliefPrice = (assets[0].amount / assets[1].amount).toFixed(18);
```
I'm able to get the bLuna balance in my wallet using:
```
const balance = await terra.wasm.contractQuery("terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp", { balance: { address: address } }); 
const blunaBalance = Object.values(balance)[0];
```
I've been following the [common example](https://docs.terra.money/SDKs/Terra-js/Common-examples.html#swapping-a-native-terra-asset-for-a-cw20-token-using-terraswap) _Swapping a native Terra asset for a CW20 token using Terraswap_. I'm not sure how I can tweak the example to swap a token to a native asset. 
```
const terraSwap = new MsgExecuteContract(
  wallet.key.accAddress,
  pool, 
  {
    swap: {
      max_spread: "0.01",
      offer_asset: {
        info: {
          native_token: {
            denom: "uusd",
          },
        },
        amount: "1000000",
      },
      belief_price: beliefPrice,
    },
  },
  new Coins({ uusd: '1000000' }),
);

```

In this example uusd is the offer_asset and is a native_token. I'm not sure how I can achieve a swap in the UST>bLuna pool since I think in this case the offer_asset would be bLuna which is a token rather than a native asset. Any help would be very appreciated. I've tried tweaking things and have run into errors and it's tricky because this can't be run on a test net.

Cheers.

**Comment by brisioksss** [comment]
also having this issue, maybe you have resolved it? Would be VERY happy to hear your results
