### ISSUE TITLE
Is there a way to lookup the token names? (I.e uluna to LUNA or uusd to UST)

### ISSUE THREAD

**Issue by alex-ald** [terra-money/terra.js#222]
Need a way to lookup the token symbols and didn't want to hard code them in my dapp.

**Comment by RomainLanz** [comment]
Hey @alex-ald! 👋🏻 

You can use the [`@terra.kitchen/utils`](https://github.com/terra-kitchen/utils) package.

```ts
import { readDenom } from '@terra.kitchen/utils'

readDenom("uluna") // "Luna"
readDenom("uusd") // "UST"
```

**Comment by alex-ald** [comment]
@RomainLanz Thanks!!
