### ISSUE TITLE
Issue with get transactions for wallet address

### ISSUE THREAD

**Issue by vaske** [terra-money/terra.js#224]
Hi there,

I notice that documentation overview from this page https://github.com/terra-money/terra.js/wiki/Querying leads to 404, anyhow I have some hard time to figure out how I can query terra properly to get latest transactions for wallet address, here is my code:

```
   const transactions = terra.tx.search({
      order_by: "ORDER_BY_DESC",
      events: [
        {
          key: "account",
          value: myAddress,
        },
      ],
    });
```

this actually dispatch API call to https://bombay-lcd.terra.dev/cosmos/tx/v1beta1/txs?pagination.key=terra1z7atcugpdexmlphtp7dwv7f8v95fzuepdy6pxd&order_by=ORDER_BY_DESC which doesn't work obviously but I found that this URL works https://bombay-fcd.terra.dev/v1/txs?offset=0&limit=100&account=terra1z7atcugpdexmlphtp7dwv7f8v95fzuepdy6pxd 

do I miss something? is there a way to call v1 from terra or make first one to works as expected?

**Comment by Vritra4** [comment]
the query you used has been sent to LCD(bombay-lcd.terra.dev) and the query you found has been sent to FCD(bombay-fcd.terra.dev). LCD doesn't have `v1/txs` endpoint.
* `cosmos/tx/v1beta1/txs` : to LCD, fetches txs by event (and tx.height have to be set for public node)
* `v1/txs`: to FCD, get tx list by predefined condition (account or block height)

you can call LCDClient.tx.search() like below:
```
await terra.tx.search({
          events: [
            { key: 'tx.height', value: '7400520' },
            { key: 'message.sender', value: "terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v" }],
          'pagination.limit': '50',
        })
```
