### ISSUE TITLE
Expected private key to be an Uint8Array with length 32

### ISSUE THREAD

**Issue by tammir1001** [terra-money/terra.js#232]
When I try to make a transaction between two of my wallets on "TERRA" I get this problem: 
Expected private key to be an Uint8Array with length 32

**Comment by Vritra4** [comment]
are you using RawKey? if so, you have to put private key Uint8Array with length 32 like the message said.
see https://github.com/terra-money/terra.js/blob/4233e49ca921a108d24f2cb0d862063d8e4b5324/src/key/RawKey.spec.ts#L42

**Comment by Umbranoctuna** [comment]
> are you using RawKey? if so, you have to put private key Uint8Array with length 32 like the message said. see
> 
> https://github.com/terra-money/terra.js/blob/4233e49ca921a108d24f2cb0d862063d8e4b5324/src/key/RawKey.spec.ts#L42

iam having a similar issue, but i dont know how to solve it. im not coding anything myself, my wallet just wont export properly.

**Comment by Vritra4** [comment]
@Umbranoctuna exported from station? if so, you need convert base64 to plain text and decrypt encrypted_key in that.
https://github.com/terra-money/station/blob/9c0a05c6d333f0d96154f41442aedc7ef0736f80/src/auth/scripts/decrypt.ts#L6

**Comment by brotherlymite** [comment]
This might be helpful: https://agora.terra.money/t/problem-generating-the-wallet-with-rawkey/2965

**Comment by Umbranoctuna** [comment]
> @Umbranoctuna exported from station? if so, you need convert base64 to plain text and decrypt encrypted_key in that. decryption reference: https://github.com/terra-money/station/blob/9c0a05c6d333f0d96154f41442aedc7ef0736f80/src/auth/scripts/decrypt.ts#L6

I tried that, but when i want to output in in the console with console.log(decrypt(mykey,mypw));
it only outputs an aski arrow up symbol, not quite sure what to make of that.
Can i contact you on discord about it?

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)

**Comment by lopezj19** [comment]
> When I try to make a transaction between two of my wallets on "TERRA" I get this problem: Expected private key to be an Uint8Array with length 32

Hello, A support ticket has been opened for you with Support ticket number TM1729. You should talk to a Terra-money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)
