### ISSUE TITLE
createAndSignTx return  `Request failed with status code 404`

### ISSUE THREAD

**Issue by seaify** [terra-money/terra.js#237]
as to this demo code, it works, but if change the URL and chainId to mainnet, get this error message, `(node:44672) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404`

```
const terra = new LCDClient({
  URL: 'https://rpc-columbus.keplr.app',
  chainID: 'columbus-5',
});
```

```
import { LCDClient, MsgSend, MnemonicKey } from '@terra-money/terra.js';

// create a key out of a mnemonic
const mk = new MnemonicKey({
  mnemonic:
    'notice oak worry limit wrap speak medal online prefer cluster roof addict wrist behave treat actual wasp year salad speed social layer crew genius',
});

// connect to bombay testnet
const terra = new LCDClient({
  URL: 'https://bombay-lcd.terra.dev',
  chainID: 'bombay-12',
});

// To use LocalTerra
// const terra = new LCDClient({
//   URL: 'http://localhost:1317',
//   chainID: 'localterra'
// });

// a wallet can be created out of any key
// wallets abstract transaction building
const wallet = terra.wallet(mk);

// create a simple message that moves coin balances
const send = new MsgSend(
  'terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v',
  'terra17lmam6zguazs5q5u6z5mmx76uj63gldnse2pdp',
  { uluna: 1000000, ukrw: 1230201, uusd: 1312029 }
);

wallet
  .createAndSignTx({
    msgs: [send],
    memo: 'test from terra.js!',
  })
  .then(tx => terra.tx.broadcast(tx))
  .then(result => {
    console.log(`TX hash: ${result.txhash}`);
  });
```

**Comment by Vritra4** [comment]
I think `https://rpc-columbus.keplr.app` is not for LCD.

**Comment by seaify** [comment]
> 

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/3056030/155269097-f0b4049b-28bb-41d8-a891-c96971d5b271.png">

switch to those LCD endpoints, also get same problem

**Comment by Vritra4** [comment]
is the error from LCD 404? not 400?

**Comment by seaify** [comment]
> is the error from LCD 404? not 400?

ah, sorry, when use the LCD endpoint, it change to "Request failed with status code 400", if use `rpc endpoint`, it's 404

**Comment by Vritra4** [comment]
did you use that mnemonic? you have to use your own mnemonic key (and derived address from it) or use testnet to confirm script works.

**Comment by hanjukim** [comment]
Can you try to catch the error for debugging?

**Comment by seaify** [comment]
> did you use that mnemonic? you have to use your own mnemonic key (and derived address from it) or use testnet to confirm script works.

when use my own mnemonic, it works at mainnet. But if change the message from transfer token to `delegate ust to anchor procotol', the error is `Request failed with status code 400`.

hm, also already catch the error

```
 const mk = new MnemonicKey({
        mnemonic: req.body.mnemonic
    });

    const terra = new LCDClient({
        URL: TERRA_URL,
        chainID: 'columbus-5'
    });

    const wallet = terra.wallet(mk);

    const msg_1 = new MsgSend(
        wallet.key.accAddress,
        'terra1jnp8ez0nlen24hr8npmjhefd2facq0x4s6lnyp',
        { uusd: 10 }
    );

    const msg = new MsgExecuteContract(
        wallet.key.accAddress,
        'terra1sepfj7s0aeg5967uxnfk4thzlerrsktkpelm5s',
        {
            deposit_stable: {},
        },
        {
            uusd: req.body.amount,
        },
    )

    console.log(msg);
    try {
        const tx = await wallet.createAndSignTx({ msgs: [msg] });
        console.log(tx);

        const result = await terra.tx.broadcast(tx);
        console.log(result);

        res.json({tx_id: result})

    }
    catch(exception) {
        console.log(exception.message);
       res.json({error: exception.message})
    }

```

**Comment by Vritra4** [comment]
@seaify `console.log(exception);`, not exception.message

**Comment by seaify** [comment]
> @seaify `console.log(exception);`, not exception.message

=> {"error"=>{"message"=>"Request failed with status code 400", "name"=>"Error", "stack"=>"Error: Request failed with status code 400\n    at createError (/home/ubuntu/cointest/releases/6179/node_modules/@terra-money/terra.js/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/home/ubuntu/cointest/releases/6179/node_modules/@terra-money/terra.js/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/home/ubuntu/coindtest/releases/6179/node_modules/@terra-money/terra.js/node_modules/axios/lib/adapters/http.js:293:11)\n    at IncomingMessage.emit (events.js:215:7)\n    at endReadableNT (_stream_readable.js:1184:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)", "config"=>{"transitional"=>{"silentJSONParsing"=>true, "forcedJSONParsing"=>true, "clarifyTimeoutError"=>false}, "transformRequest"=>[nil], "transformResponse"=>[nil], "timeout"=>30000, "xsrfCookieName"=>"XSRF-TOKEN", "xsrfHeaderName"=>"X-XSRF-TOKEN", "maxContentLength"=>-1, "maxBodyLength"=>-1, "headers"=>{"Accept"=>"application/json", "Content-Type"=>"application/json", "User-Agent"=>"axios/0.24.0", "Content-Length"=>367}, "baseURL"=>"https://lcd.terra.dev", "method"=>"post", "url"=>"/cosmos/tx/v1beta1/simulate", "data"=>"{\"tx_bytes\":\"CqsBCqgBCiYvdGVycmEud2FzbS52MWJldGExLk1zZ0V4ZWN1dGVDb250cmFjdBJ+Cix0ZXJyYTE2aDNjZ2gwZ2x5dzltY3h1cGMwbHp3Z3hxbHh1ZDg0dm0yZHkwNxIsdGVycmExc2VwZmo3czBhZWc1wfewfewOTY3dXhuZms0dGh6bGVycnNrdGtwZWxtNXMaFXsiZGVwb3NpdF9zdGFibGUiOnt9fSoJCgR1dXNkEgExElQKUApGCh8vY29zbW9zLmNyeXB0by5zZWNwMjU2azEuUHViS2V5EiMKIQJV/2QHBapKLGljbO/GgUPwZm3xaHc90HTn8C2JsdIvGhIECgIIARgxEgAaAA==\"}"}, "status"=>400}}

**Comment by loveFeynman** [comment]
Hi, @seaify 
Did you fix that error `Request failed with status code 400`?
I faced that issue, so I'd like to know how to solve that issue
Thanks.

**Comment by seaify** [comment]
> that

sorry, nope

**Comment by coder-chenda** [comment]
timeout"=>30000  ，I also encountered the same problem, and they all appeared frequently

**Comment by coder-chenda** [comment]
> > 
> 
> <img alt="image" width="1233" src="https://user-images.githubusercontent.com/3056030/155269097-f0b4049b-28bb-41d8-a891-c96971d5b271.png">
> 
> switch to those LCD endpoints, also get same problem

Hello, have you met this problem, too? I've met this problem for months. Have you solved it?

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)

**Comment by afoxaccnos** [comment]
seem to be having a very similar issue. Looks to be some issue when simulating the transaction with the node to get the gas prices I believe. Have tried using different LCD endpoints. Any help appreciated

**Comment by afoxaccnos** [comment]
Found the issue, 
The 400 error masks the actual underlying error from the endpoint.
So you need to more deeply inspect the returning message.  
Creating a raw post message from that error output and looking at that might be the easiest way to do see it, if you can't inspect from your code editor.

In my case I was sending a larger value than my balance, so the gas simulation transaction was failing on that.

e.g.

{
  "code": 3,
  "message": "failed to execute message; message index: 0: 996465uluna is smaller than 1000000uluna: insufficient funds: invalid request",
  "details": [
  ]
}

**Comment by seaify** [comment]
> Found the issue, The 400 error masks the actual underlying error from the endpoint. So you need to more deeply inspect the returning message. Creating a raw post message from that error output and looking at that might be the easiest way to do see it, if you can't inspect from your code editor.
> 
> In my case I was sending a larger value than my balance, so the gas simulation transaction was failing on that.
> 
> e.g.
> 
> { "code": 3, "message": "failed to execute message; message index: 0: 996465uluna is smaller than 1000000uluna: insufficient funds: invalid request", "details": [ ] }

hi, thanks for your remind, finally it works.

if use `javascript`, check  `exception.response.data` for detailed error message.

now attach the working code, mainly need to add `fee`

```
    const mk = new MnemonicKey({
        mnemonic: req.body.mnemonic
    });

    const terra = new LCDClient({
        URL: TERRA_URL,
        chainID: 'columbus-5'
    });

    const wallet = terra.wallet(mk);

    const msg = new Terra.MsgExecuteContract(
        wallet.key.accAddress,
        'terra1sepfj7s0aeg5967uxnfk4thzlerrsktkpelm5s',
        {
            deposit_stable: {},
        },
        {
            uusd: req.body.amount,
        },
    )

    const fee = new Terra.Fee(800000, { uluna: '10000' })

    try {
        const tx = await wallet.createAndSignTx({ msgs: [msg], fee: fee });
        const result = await terra.tx.broadcast(tx);
        res.json({tx_id: result})
    }
    catch(exception) {
       res.json({error: exception.response.data})
    }
```
