### ISSUE TITLE
Question: Coin Parsing

### ISSUE THREAD

**Issue by olvresc** [terra-money/terra.js#239]
Hello, I'm trying to send the UST from one account to another account. 

I was able to send and received the UST on my account using `uusd` as denom. 

```
const mnemonic = new MnemonicKey({ mnemonic: "" });
const wallet = terra.wallet(mnemonic);
const transaction = new MsgSend(
  wallet.key.accAddress,
  options.recipient,
  { uusd: 9749344 }
);
        
await wallet.createAndSignTx({
  msgs: [transaction],
  memo: "",
});
```

Is there a util that parse a custom amount inputted?

Ex: I want to transfer 97.493442 UST

How should I parse it to be a `uusd`? I know I can remove the `.` but is there any class/function that I can use?

**Comment by Vritra4** [comment]
1UST = 1,000,000uusd. just multiplication will work.

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)
