### ISSUE TITLE
Allow increase api request timeout

### ISSUE THREAD

**Issue by jiqiang90** [terra-money/terra.js#241]
Hi in our project we are having timeout issue while fetch some blocks, 

```
Error: timeout of 30000ms exceeded at createError (/usr/local/lib/node_modules/@subql/node-terra/node_modules/@terra-money/terra.js/node_modules/axios/lib/core/createError.js:16:15) 
```

https://github.com/terra-money/terra.js/blob/9e5f553de3ff3e975eaaf91b1f06e45658b1a5e0/src/client/lcd/APIRequester.ts#L31

Is that possible to add an option allow us to manually increase the timeout? Thank you

**Comment by Vritra4** [comment]
30s of timeout is long enough i think. did you query to public lcd?

**Comment by coder-chenda** [comment]
I also encountered the same problem, and they all appeared frequently

**Comment by RomainLanz** [comment]
Hey! 👋🏻 

If you are using the public LCD, maybe you should verify that you are not rate-limited.
Spamming too much the endpoint will get you banned for some time.

**Comment by jiqiang90** [comment]
@RomainLanz Thank you.

**Comment by Vritra4** [comment]
@jiqiang90 seems okay to close. feel free to reopen it if you want.
