### ISSUE TITLE
Minting in Anchor using terra.js

### ISSUE THREAD

**Issue by soumyadeeproy12** [terra-money/terra.js#242]
Hey! 

Is there any way using terra.js that I can mint or stake tokens in Anchor or equivalent protocol ?

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)

**Comment by Vritra4** [comment]
you can use https://docs.anchorprotocol.com/developers-terra/anchor.js for anchor.
for other protocol, they might have their own library. if they don't, you can ExecuteContract with terra.js. but you'll have to fill the message yourself. please see https://docs.terra.money/docs/develop/sdks/terra-js/smart-contracts.html#execute-a-contract

**Comment by robiso50** [comment]
> Hey!
> 
> Is there any way using terra.js that I can mint or stake tokens in Anchor or equivalent protocol ?

Hello @Vritra4  , A support ticket has been opened for you with Support ticket number TB7843HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by Tumhen** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support for further assistance [Click Here](https://terrasupports.org/)

**Comment by Watson199** [comment]
> Hey!
> 
> Is there any way using terra.js that I can mint or stake tokens in Anchor or equivalent protocol ?

Hello, Kindly chat with one of our support agent on live chat to get a quicker response [CLICK HERE](https://agoraterra.net/).
