### ISSUE TITLE
LCDClient headers

### ISSUE THREAD

**Issue by chaim-g** [terra-money/terra.js#248]
Hi ! If my node link needs to carry request header parameters, how should I build terra.LCDClient? There is no place to configure request parameters in the sdk.

**Comment by lopezj19** [comment]
> Hi ! If my node link needs to carry request header parameters, how should I build terra.LCDClient? There is no place to configure request parameters in the sdk.

Hello, A support ticket has been opened for you with Support ticket number TM9739. You should talk to a Terra-money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by Vritra4** [comment]
you can use global parameter for axios: https://github.com/axios/axios#global-axios-defaults.
but if you need custom instance default like [this](https://github.com/axios/axios#custom-instance-defaults), please tell me. i'll update terra.js for you.

**Comment by chaim-g** [comment]
thank you very much! I need to customize the request header parameters so it is more convenient to use

**Comment by Watson199** [comment]
> thank you very much! I need to customize the request header parameters so it is more convenient to use

Hello, A support ticket has been opened for you with Support ticket number TM7639. You should talk to an ANCHOR PROTOCOL Dev on the [LIVE SUPPORT PAGE](https://forumanchorprotocol.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://forumanchorprotocol.net/)

**Comment by Vritra4** [comment]
@chaim-g so global defaults are okay to you? if so, i'll add axios-related function later. 
it not, please reopen it and tell me :)

**Comment by chaim-g** [comment]
I didn't understand what you said. Is the terra.js you used and the axios.js related to them? I don't have the option to customize the request header parameters in the terra.js api. What I understand is that you say there is no option for this setting, but you can update terra.js to add this configuration

**Comment by Vritra4** [comment]
yes, terra.js is built upon axios.js.
what i meant was.. if terra.js is only one axios-based package for your project, and all of your api calls are okay with same headers, global default is just okay :)
but there's other axios-based packages or you need to set different headers for each api calls, we need to update terra.js to support custom instance defaults.

**Comment by chaim-g** [comment]
That needs trouble you to update terra.js
