### ISSUE TITLE
TypeError: e.isPoint is not a function, 

### ISSUE THREAD

**Issue by realkibou** [terra-money/terra.js#251]
Hi,

just made a fresh Vite-Project (npm create vite@latest), Javascript, vanilla and I am using the the terra.js in the browser with `<script  crossorigin  src="https://unpkg.com/@terra-money/terra.js/dist/bundle.js"></script>`

However, I am getting the following error in the console:
Uncaught TypeError: e.isPoint is not a function
    at Object.t.testEcc (testecc.js:5:16)
    at t.BIP32Factory (bip32.js:9:15)
    at new t (MnemonicKey.ts:82:19)
    at main.js:14:12

with 

`const mk = new Terra.MnemonicKey({
  mnemonic: 'apple apple banana banana xxx',
});`

This error in the the testecc.js is in the last line here:
`"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const h = (hex) => Buffer.from(hex, 'hex');
function testEcc(ecc) {
    assert(ecc.isPoint(h('0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798')));`

**Comment by Jodilopez** [comment]
> Hi,
> 
> just made a fresh Vite-Project (npm create vite@latest), Javascript, vanilla and I am using the the terra.js in the browser with `<script crossorigin src="https://unpkg.com/@terra-money/terra.js/dist/bundle.js"></script>`
> 
> However, I am getting the following error in the console: Uncaught TypeError: e.isPoint is not a function at Object.t.testEcc (testecc.js:5:16) at t.BIP32Factory (bip32.js:9:15) at new t (MnemonicKey.ts:82:19) at main.js:14:12
> 
> with
> 
> `const mk = new Terra.MnemonicKey({ mnemonic: 'apple apple banana banana xxx', });`
> 
> This error in the the testecc.js is in the last line here: `"use strict"; Object.defineProperty(exports, "__esModule", { value: true }); const h = (hex) => Buffer.from(hex, 'hex'); function testEcc(ecc) { assert(ecc.isPoint(h('0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798')));`

Hello @thinkingparticle , A support ticket has been opened for you with Support ticket number TB7836AS. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by sebastianupr** [comment]
I have the same problem, any solution for this?

**Comment by ranahammad415** [comment]
I have also the same issue, have you found any solution ? please

**Comment by ranahammad415** [comment]
i have found the solution for this. you can use this cdn for terra.js library https://cdn.jsdelivr.net/npm/@terra-money/terra.js@3.0.9/dist/bundle.js

**Comment by bridget432** [comment]
> I have the same problem, any solution for this?

Hi @sebastianupr I will suggest you contact Terra support and talk with a Developer from Terra through their live chat Developers forum. Click on the  Forum ——>> [TERRA DEVELOPERS LIVE CHAT](https://agora.terras.live/) To help you sort this out right away

**Comment by hanjukim** [comment]
The error was caused by bip32 upgrade. It's reverted now.
