### ISSUE TITLE
Support for programmatic multi-sig wallet generation

### ISSUE THREAD

**Issue by niyogi** [terra-money/terra.js#258]
Any plans to create a method to programmatically generate a multi-sig wallet?

Ideally pass in X number of addresses and a threshold and a multi-sig wallet address is generated?

**Comment by ericHgorski** [comment]
Hi @niyogi, this repository may be of interest: https://github.com/octalmage/multisig.money

If you can't find answers there then please reach out on Discord in the future: https://discord.gg/Tc2BNUz8EH
