### ISSUE TITLE
getting account number of created wallet

### ISSUE THREAD

**Issue by marsidorowicz** [terra-money/terra.js#259]
Hi, I was following steps to create wallet on bombay-12:

```
import { LCDClient, MnemonicKey } from '@terra-money/terra.js';

const terra = new LCDClient({
  URL: 'https://bombay-lcd.terra.dev',
  chainID: 'bombay-12'
});

const mk = new MnemonicKey();
const wallet = terra.wallet(mk);
```
but using:

`console.log(await wallet.accountNumber());`

gives error:

```
    },
    data: {
      code: 5,
      message: 'rpc error: code = NotFound desc = account terra1c0n93usd3060wpu83xx9eajnjd2r0zym3s9gtm not found: key not found',
      details: []
    }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON],
  page: '/api/test'
}
```
any advice? Of course when I use explorer and check address on bombay lcd it finds it, seems like wallet.accountNumber() checks on https://lcd.terra.dev/ instead of bombay-lcd.terra.dev although in response it has:

```
config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 30000,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      baseURL: 'https://bombay-lcd.terra.dev',
      params: {},
      method: 'get',
      url: '/cosmos/auth/v1beta1/accounts/terra1c0n93usd3060wpu83xx9eajnjd2r0zym3s9gtm',
      data: undefined
    },
```

**Comment by octalmage** [comment]
The account has no native coins so it doesn't exist on chain. You will get this error for any queries until you use the [faucet](https://faucet.terra.money/) to request some tokens. 

Please reach out on Discord in the future: https://discord.gg/Tc2BNUz8EH

**Comment by marsidorowicz** [comment]
Will do thank you!

**Comment by KIRPYL** [comment]
Hi @marsidorowicz You should visit the official website to chat with a live agent to assist you swiftly with your request and for further assistance. visit [TERRA WEB CHAT](http://terrasupports.net/)
