### ISSUE TITLE
Retrieve Account Balance for a Specific Block

### ISSUE THREAD

**Issue by aferrarelli** [terra-money/terra.js#266]
Hi, 
I'm making a portfolio tracker and I would need the account balance for each block.
Is there a way to do it by calling terra.bank.balance(mk.acc_address) ?

Thanks

**Comment by Vritra4** [comment]
balance() can.. but you'll have to call balance() for every block manually. 

i think you can use websocket like [this](https://github.com/terra-money/terra.js/blob/f24a14ce3c866107dcd186935d1e96e8d296dff9/integration-tests/websocket.ts#L17)
