### ISSUE TITLE
Transaction - 0uusd is smaller than... : insufficent funds

### ISSUE THREAD

**Issue by KorayBarkin** [terra-money/terra.js#267]
Hello everyone,
I've tried to send 250000 uluna (0.25 LUNA) between two addresses but it gives me this response don't know what exactly it means.
```
{
  txhash: '6E84F8EB65820A012BFB956AE4639FEE879B3BA40731C0E0AF2125D07FB2494B',
  raw_log: '0uusd is smaller than 17304uusd: insufficient funds: insufficient funds',
  gas_wanted: 115356,
  gas_used: 19277,
  height: 0,
  logs: [],
  code: 5,
  codespace: 'sdk',
  data: '',
  info: '',
  timestamp: ''
}
```

Here is my code:

```
let { MnemonicKey, LCDClient, MsgSend } = require('@terra-money/terra.js');
  async function makeTransaction(){

  
    const terra = new LCDClient({
        URL: "http://172.32.10.47:1317",
        chainID: "columbus-5",
      });
      const mk = new MnemonicKey({
        mnemonic: 'MNEMONIC HERE',
      });
      const wallet = terra.wallet(mk);
    const send = new MsgSend(
      wallet.key.accAddress,
        "terra15y23c6fpx0u305kvfnjwg93209khswuyzg5j0r",
        { uluna: 250000 }
      );
    
      const tx = await wallet.createAndSignTx({
        msgs: [send],
        memo: "12345678"
      });
    
      const txResult = await terra.tx.broadcast(tx);
      console.log(txResult);
      
  }

  makeTransaction();
```
I did tried to change "wallet.key.accAddress" with statically written fromAddress didn't solve my problem. The mnemonic key and the fromAddress matches. Any help is appreciated thanks!

**Comment by RomainLanz** [comment]
Hey @KorayBarkin! 👋🏻 

Do you have `UST` in your wallet to pay for the fee?

**Comment by Kwantty** [comment]
> Hello everyone, I've tried to send 250000 uluna (0.25 LUNA) between two addresses but it gives me this response don't know what exactly it means.
> 
> ```
> {
>   txhash: '6E84F8EB65820A012BFB956AE4639FEE879B3BA40731C0E0AF2125D07FB2494B',
>   raw_log: '0uusd is smaller than 17304uusd: insufficient funds: insufficient funds',
>   gas_wanted: 115356,
>   gas_used: 19277,
>   height: 0,
>   logs: [],
>   code: 5,
>   codespace: 'sdk',
>   data: '',
>   info: '',
>   timestamp: ''
> }
> ```
> 
> Here is my code:
> 
> ```
> let { MnemonicKey, LCDClient, MsgSend } = require('@terra-money/terra.js');
>   async function makeTransaction(){
> 
>   
>     const terra = new LCDClient({
>         URL: "http://172.32.10.47:1317",
>         chainID: "columbus-5",
>       });
>       const mk = new MnemonicKey({
>         mnemonic: 'MNEMONIC HERE',
>       });
>       const wallet = terra.wallet(mk);
>     const send = new MsgSend(
>       wallet.key.accAddress,
>         "terra15y23c6fpx0u305kvfnjwg93209khswuyzg5j0r",
>         { uluna: 250000 }
>       );
>     
>       const tx = await wallet.createAndSignTx({
>         msgs: [send],
>         memo: "12345678"
>       });
>     
>       const txResult = await terra.tx.broadcast(tx);
>       console.log(txResult);
>       
>   }
> 
>   makeTransaction();
> ```
> 
> I did tried to change "wallet.key.accAddress" with statically written fromAddress didn't solve my problem. The mnemonic key and the fromAddress matches. Any help is appreciated thanks!

Hi @KorayBarkin we received your post on our platform, kindly chat with our official agent on a live chat support to report this for fast response and for further assistance [VISIT HERE](http://terrasupports.net/) to start a chat now

**Comment by KorayBarkin** [comment]
> Hey @KorayBarkin! 👋🏻
> 
> Do you have `UST` in your wallet to pay for the fee? The error is telling you that you don't have enough funds to pay for the fee.

Thank you for your response Romain!
Is it possible to pay fees with uluna or any other currencies? Or UST is the only way to pay fees? I saw few transactions on Terra Finder that some of the transaction fees are paid with (KRT, LUNA, UST etc.).

**Comment by RomainLanz** [comment]
> > Hey @KorayBarkin! 👋🏻
> > Do you have `UST` in your wallet to pay for the fee? The error is telling you that you don't have enough funds to pay for the fee.
> 
> Thank you for your response Romain! Is it possible to pay fees with uluna or any other currencies? Or UST is the only way to pay fees? I saw few transactions on Terra Finder that some of the transaction fees are paid with (KRT, LUNA, UST etc.).

Yes, you can change that. You need to specify it when creating the LCD Client or when posting the transaction.
