### ISSUE TITLE
calculate transaction hash before broadcast

### ISSUE THREAD

**Issue by avolkov-dev** [terra-money/terra.js#269]
I was not able to find the way to calculate hash of the signed transaction.
Could you help me to figure out that?

**Comment by Vritra4** [comment]
you can get hash from tx using LCDCLient.tx.hash()

**Comment by Weaverij** [comment]
> I was not able to find the way to calculate hash of the signed transaction. Could you help me to figure out that?

Hello, A support ticket has been opened for you with Support ticket number NM27836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by avolkov-dev** [comment]
thanks @Vritra4

**Comment by Weaverij** [comment]
> I was not able to find the way to calculate hash of the signed transaction. Could you help me to figure out that?

Hello, A support ticket has been opened for you with Support ticket number TB73HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)
