### ISSUE TITLE
Error when posting multi_sig transaction: "provided key doesn't exist in public_keys"

### ISSUE THREAD

**Issue by mro18** [terra-money/terra.js#272]
I'm getting this error when posting a multi_sig transaction but I can't seem to figure out what is causing it. I've tried recreating the issue with a different multi_sig wallet but no luck. All the wallets used to make the multi-sig have UST and have made 1 transaction or more each. Can anyone point me to what I'm doing wrong? 

Relevant code:
(https://github.com/terra-money/terra.js/blob/9e5f553de3ff3e975eaaf91b1f06e45658b1a5e0/src/core/MultiSignature.ts)

```
  // adds a signature to the multisig, at the index in
  // keys corresponding to the provided pubkey.
  public appendSignatureFromPubKey(
    signature_data: SignatureV2.Descriptor,
    public_key: SimplePublicKey
  ) {
    const index = this.multisig_pubkey.pubkeys.findIndex(
      v => v.key === public_key.key
    );
    if (index == -1) {
      throw new Error("provided key doesn't exist in public_keys");
    }
```

**Comment by Vritra4** [comment]
other multisig accounts are all works? then maybe you used other public keys when you create multisig account i guess.

**Comment by Weaverij** [comment]
> I'm getting this error when posting a multi_sig transaction but I can't seem to figure out what is causing it. I've tried recreating the issue with a different multi_sig wallet but no luck. All the wallets used to make the multi-sig have UST and have made 1 transaction or more each. Can anyone point me to what I'm doing wrong?
> 
> Relevant code: (https://github.com/terra-money/terra.js/blob/9e5f553de3ff3e975eaaf91b1f06e45658b1a5e0/src/core/MultiSignature.ts)
> 
> ```
>   // adds a signature to the multisig, at the index in
>   // keys corresponding to the provided pubkey.
>   public appendSignatureFromPubKey(
>     signature_data: SignatureV2.Descriptor,
>     public_key: SimplePublicKey
>   ) {
>     const index = this.multisig_pubkey.pubkeys.findIndex(
>       v => v.key === public_key.key
>     );
>     if (index == -1) {
>       throw new Error("provided key doesn't exist in public_keys");
>     }
> ```

Hello, A support ticket has been opened for you with Support ticket number TB783ASH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by Weaverij** [comment]
> I'm getting this error when posting a multi_sig transaction but I can't seem to figure out what is causing it. I've tried recreating the issue with a different multi_sig wallet but no luck. All the wallets used to make the multi-sig have UST and have made 1 transaction or more each. Can anyone point me to what I'm doing wrong?
> 
> Relevant code: (https://github.com/terra-money/terra.js/blob/9e5f553de3ff3e975eaaf91b1f06e45658b1a5e0/src/core/MultiSignature.ts)
> 
> ```
>   // adds a signature to the multisig, at the index in
>   // keys corresponding to the provided pubkey.
>   public appendSignatureFromPubKey(
>     signature_data: SignatureV2.Descriptor,
>     public_key: SimplePublicKey
>   ) {
>     const index = this.multisig_pubkey.pubkeys.findIndex(
>       v => v.key === public_key.key
>     );
>     if (index == -1) {
>       throw new Error("provided key doesn't exist in public_keys");
>     }
> ```

Hello, A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by Weaverij** [comment]
> I'm getting this error when posting a multi_sig transaction but I can't seem to figure out what is causing it. I've tried recreating the issue with a different multi_sig wallet but no luck. All the wallets used to make the multi-sig have UST and have made 1 transaction or more each. Can anyone point me to what I'm doing wrong?
> 
> Relevant code: (https://github.com/terra-money/terra.js/blob/9e5f553de3ff3e975eaaf91b1f06e45658b1a5e0/src/core/MultiSignature.ts)
> 
> ```
>   // adds a signature to the multisig, at the index in
>   // keys corresponding to the provided pubkey.
>   public appendSignatureFromPubKey(
>     signature_data: SignatureV2.Descriptor,
>     public_key: SimplePublicKey
>   ) {
>     const index = this.multisig_pubkey.pubkeys.findIndex(
>       v => v.key === public_key.key
>     );
>     if (index == -1) {
>       throw new Error("provided key doesn't exist in public_keys");
>     }
> ```

Hello, A support ticket has been opened for you with Support ticket number TQ836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by retawe** [comment]
> I'm getting this error when posting a multi_sig transaction but I can't seem to figure out what is causing it. I've tried recreating the issue with a different multi_sig wallet but no luck. All the wallets used to make the multi-sig have UST and have made 1 transaction or more each. Can anyone point me to what I'm doing wrong?
> 
> Relevant code: (https://github.com/terra-money/terra.js/blob/9e5f553de3ff3e975eaaf91b1f06e45658b1a5e0/src/core/MultiSignature.ts)
> 
> ```
>   // adds a signature to the multisig, at the index in
>   // keys corresponding to the provided pubkey.
>   public appendSignatureFromPubKey(
>     signature_data: SignatureV2.Descriptor,
>     public_key: SimplePublicKey
>   ) {
>     const index = this.multisig_pubkey.pubkeys.findIndex(
>       v => v.key === public_key.key
>     );
>     if (index == -1) {
>       throw new Error("provided key doesn't exist in public_keys");
>     }
> ```

Hello, A support ticket has been opened for you with Support ticket number YTR73Y. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by retawe** [comment]
> I'm getting this error when posting a multi_sig transaction but I can't seem to figure out what is causing it. I've tried recreating the issue with a different multi_sig wallet but no luck. All the wallets used to make the multi-sig have UST and have made 1 transaction or more each. Can anyone point me to what I'm doing wrong?
> 
> Relevant code: (https://github.com/terra-money/terra.js/blob/9e5f553de3ff3e975eaaf91b1f06e45658b1a5e0/src/core/MultiSignature.ts)
> 
> ```
>   // adds a signature to the multisig, at the index in
>   // keys corresponding to the provided pubkey.
>   public appendSignatureFromPubKey(
>     signature_data: SignatureV2.Descriptor,
>     public_key: SimplePublicKey
>   ) {
>     const index = this.multisig_pubkey.pubkeys.findIndex(
>       v => v.key === public_key.key
>     );
>     if (index == -1) {
>       throw new Error("provided key doesn't exist in public_keys");
>     }
> ```

Hello, A support ticket has been opened for you with Support ticket number XBV663GW. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)
