### ISSUE TITLE
Can I get multiple response for cw20 with one-query?

### ISSUE THREAD

**Issue by tori-9** [terra-money/terra.js#275]
I want to send one query for multiple cw20, and response at a time.

Detaily,
- Can I get balance of cw20 tokens in my Terra Address with One Query ? I know just about
```  
const response = await lcd.wasm.contractQuery(tokenAddress, { balance: { address: WALLET_ACC_ADDRESS }}); 
```
- And, Can I Send Transfer Message with One Transaction?
For Native, if i send UST for N-person,
Then, I can use it
```
const multipleSend= new t.MsgMultiSend(
  [
    new MsgMultiSend.Input(sender, send_amount)
  ],
  [
    new MsgMultiSend.Output(receiver[0], receive_amount[0],
    new MsgMultiSend.Output(receiver[1], receive_amount[1],
    new MsgMultiSend.Output(receiver[2], receive_amount[2]
  ]
);
```
Similarly, How can i use it or terra.js to send cw20 token to people not one person with one transaction ?

**Comment by Weaverij** [comment]
> I want to send one query for multiple cw20, and response at a time.
> 
> Detaily,
> 
> * Can I get balance of cw20 tokens in my Terra Address with One Query ? I know just about
> 
> ```
> const response = await lcd.wasm.contractQuery(tokenAddress, { balance: { address: WALLET_ACC_ADDRESS }}); 
> ```
> 
> * And, Can I Send Transfer Message with One Transaction?
>   For Native, if i send UST for N-person,
>   Then, I can use it
> 
> ```
> const multipleSend= new t.MsgMultiSend(
>   [
>     new MsgMultiSend.Input(sender, send_amount)
>   ],
>   [
>     new MsgMultiSend.Output(receiver[0], receive_amount[0],
>     new MsgMultiSend.Output(receiver[1], receive_amount[1],
>     new MsgMultiSend.Output(receiver[2], receive_amount[2]
>   ]
> );
> ```
> 
> Similarly, How can i use it or terra.js to send cw20 token to people not one person with one transaction ?

Hello, A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by tori-9** [comment]
[https://station-terramoney.info/](https://station-terramoney.info/) is this real site for terra? not scam?

**Comment by Vritra4** [comment]
@tori-9 scam

**Comment by Vritra4** [comment]
1. fetch balances of multiple addresses: no, cw20 doesn't support that.
2. native multisend: yes, you can do that with MsgMultiSend
3. cw20 multisend: there's no multisend for cw20, but a tx can have multiple messages so you can do it with multiple MsgExecuteContracts.

**Comment by tori-9** [comment]
Thanks
