### ISSUE TITLE
Can i get public key from only accAddress?

### ISSUE THREAD

**Issue by tori-9** [terra-money/terra.js#277]
Suppose my terra accAddress is terra1234~~~

Then Can i get public key with accAddress string only?

**Comment by retawe** [comment]
> Suppose my terra accAddress is terra1234~~~
> 
> Then Can i get public key with accAddress string only?

Hello, A support ticket has been opened for you with Support ticket number MNS37UE. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by retawe** [comment]
> Suppose my terra accAddress is terra1234~~~
> 
> Then Can i get public key with accAddress string only?

Hello, A support ticket has been opened for you with Support ticket number BBNHYEU. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by retawe** [comment]
> Suppose my terra accAddress is terra1234~~~
> 
> Then Can i get public key with accAddress string only?

Hello, A support ticket has been opened for you with Support ticket number BN6776TY. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by Vritra4** [comment]
call LCDClient.auth.accountInfo(). it returns public key.
if the address is not used to make a transaction, public key will be empty.
