### ISSUE TITLE
How to retrieve CW20 token details

### ISSUE THREAD

**Issue by uvindu9412** [terra-money/terra.js#278]
How can we retrieve name, symbol, decimals data of a cw20 token ?

**Comment by retawe** [comment]
> How can we retrieve name, symbol, decimals data of a cw20 token ?

Hello, A support ticket has been opened for you with Support ticket number HD74UDH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by retawe** [comment]
> How can we retrieve name, symbol, decimals data of a cw20 token ?

Hello, A support ticket has been opened for you with Support ticket number RFY677H. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by retawe** [comment]
> How can we retrieve name, symbol, decimals data of a cw20 token ?

Hello, A support ticket has been opened for you with Support ticket number VB566N. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by sammiyee** [comment]
> How can we retrieve name, symbol, decimals data of a cw20 token ?

Hello, A support ticket has been opened for you with Support ticket number BV3443BV. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by Vritra4** [comment]
call LCDCLient.wasm.contractInfo(). it returns init_msg and the msg contains some information about that.
