### ISSUE TITLE
By blockHeight get balance.

### ISSUE THREAD

**Issue by cao148** [terra-money/terra.js#281]
Excuse me, I want to get Terra's address balance at the specified block height, what should I do.

**Comment by Vritra4** [comment]
call LCDClient.bank.balance() with height in second param.
like `await pisco.bank.balance("terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v", { height: 46191 });`
but public lcd may not accept this. use your own node to be sure.
