### ISSUE TITLE
Previously, the old chain used Terra Can the code developed by JS be directly used to develop the new chain Terra?

### ISSUE THREAD

**Issue by coder-chenda** [terra-money/terra.js#287]
For example, the old code broadcast sending transaction can be used to the new chain, but the URL configured in the lcdclient is different from the chain ID through is_ Classic to set which client to use. The call and return information of these interfaces are compatible and unchanged. I want to confirm.

**Comment by Vritra4** [comment]
yes terra.js ^3.1.0 supports both chain.
some methods need to be called with isClassic flag to determine target network.
set isClassic to true when you interact with columbus-5 network and stay with default or set to false when you intarct with phoenix-1 network.
