### ISSUE TITLE
Use https://phoenix-lcd.terra.dev Get transaction timeout

### ISSUE THREAD

**Issue by coder-chenda** [terra-money/terra.js#292]
{"error":{"message":"Request failed with status code 400","name":"Error","stack":"Error: Request failed with status code 400\n    at createError (/Users/chenda/Documents/develop/docker_conf/luna/node-js/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/Users/chenda/Documents/develop/docker_conf/luna/node-js/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/Users/chenda/Documents/develop/docker_conf/luna/node-js/node_modules/axios/lib/adapters/http.js:322:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1334:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":30000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"headers":{"Accept":"application/json","User-Agent":"axios/0.26.1"},"params":{},"method":"get","url":"https://phoenix-lcd.terra.dev/cosmos/base/tendermint/v1beta1/blocks/7836973"}

**Comment by Vritra4** [comment]
requested block height is bigger than the height of phoenix-1
