### ISSUE TITLE
the block latest height is always 56602(tendermintAPI)

### ISSUE THREAD

**Issue by 1486327116** [terra-money/terra.js#302]
when  i use tendermint.blockInfo(undefined) to get the header's latest block height ,the response is always 56602 ,
and the client is :
```
let Client = new LCDClient({
            URL: 'https://phoenix-lcd.terra.dev',
            chainID: 'phoenix-1',
            isClassic:false 
 });
```

**Comment by citizenpurpur** [comment]
Looks like it's using this cosmos call which always returns 56602
https://phoenix-lcd.terra.dev/swagger/#/Service/GetLatestBlock
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/97715590/172039610-cc0b892c-ff12-4dc3-8ff3-b9baf022d084.png">



This one works fine and returns latest
https://phoenix-lcd.terra.dev/swagger/#/Tendermint_RPC/get_blocks_latest
<img width="991" alt="image" src="https://user-images.githubusercontent.com/97715590/172039616-a00d872f-55c6-4d3d-8c77-6027bcf496f3.png">

**Comment by 1486327116** [comment]
> Looks like it's using this cosmos call which always returns 56602 https://phoenix-lcd.terra.dev/swagger/#/Service/GetLatestBlock <img alt="image" width="991" src="https://user-images.githubusercontent.com/97715590/172039616-a00d872f-55c6-4d3d-8c77-6027bcf496f3.png">
> 
> This one works fine and returns latest https://phoenix-lcd.terra.dev/swagger/#/Tendermint_RPC/get_blocks_latest <img alt="image" width="1055" src="https://user-images.githubusercontent.com/97715590/172039610-cc0b892c-ff12-4dc3-8ff3-b9baf022d084.png">
> 
> Get BlockByHeight also works if specifying latest block https://phoenix-lcd.terra.dev/swagger/#/Service/GetBlockByHeight <img alt="image" width="1196" src="https://user-images.githubusercontent.com/97715590/172039779-8f7f5832-191a-43a5-9fc8-43bd8ee0cd50.png">

Thank u , now i can working with the  new url requset https://phoenix-lcd.terra.dev/blocks/latest
