### ISSUE TITLE
Same API, different return results

### ISSUE THREAD

**Issue by coder-chenda** [terra-money/terra.js#310]
Hello, everyone. I want to ask a question, why do you call const blockinfo = await api tendermint. Blockinfo (height) does not return the latest block?
![image](https://user-images.githubusercontent.com/83049018/176491012-4587ba4b-7626-4935-a955-aff536139b8a.png)

For the same SDK, the version is the same, but the results are different on the local and server. The local returns the latest height, but the server does not
![image](https://user-images.githubusercontent.com/83049018/176491055-8c19445c-20c0-4055-86b8-49088e4c2b81.png)

I printed out the API information，
![r8b2PNBvXZ](https://user-images.githubusercontent.com/83049018/176491200-ba710ce3-b613-4dda-982e-c240d715fe22.png)

![eghhfF4Gqe](https://user-images.githubusercontent.com/83049018/176491228-5010f2cf-070a-4e54-be9c-559f2b44cd8b.png)

I printed out the API information, and the results were the same, but by calling const blockinfo = await api tendermint. Blockinfo (height) returns different results, one locally and the other on the server I can't imagine why the information printed by the API is the same, but the blockinfo obtained by calling the same method is different?

**Comment by coder-chenda** [comment]
my code is 
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/83049018/176492086-d21dab1a-de8e-4645-a5a3-196bd9879bca.png">

**Comment by Vritra4** [comment]
you mean difference between public LCD and your own node? maybe your own node isn't fully synchronized.

**Comment by coder-chenda** [comment]
> you mean difference between public LCD and your own node? maybe your own node isn't fully synchronized.

I use public official nodes, servers refer to cloud servers, and local refers to my own dotcom, but I use official nodes https://phoenix-lcd.terra.dev/ For foreign servers, the intelligent access to the height reached a month ago, and domestic machines are normal. I don't know if there are any restrictions. The public nodes that apply for access to the latest height information are normal

**Comment by hanjukim** [comment]
> my code is <img alt="image" width="1013" src="https://user-images.githubusercontent.com/83049018/176492086-d21dab1a-de8e-4645-a5a3-196bd9879bca.png">

await this.terra # Invalid. await should be used when calling a function, but it's trivial...

For you question, I think your local node is not synchronized. Try to query your local node e.g. `curl localhost:1317/blocks/latest | jq .block.header`
