### ISSUE TITLE
CreateTxFailed: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by gameveloster** [terra-money/terra.js#312]
Hi, I'm getting this error

>   CreateTxFailed: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

when I use Terra Station Wallet 3.0.6 on Chrome to post a "Luna Classic" transaction created by my React app using the code:

```js
const connectedWallet = useConnectedWallet();

...

        const { result } = await connectedWallet.post({
          msgs: [
            new MsgExecuteContract(
              connectedWallet.terraAddress,
              counterAddr,
              executeMsg,
              { uluna: 100000 },
            ),
          ],
          fee
        });
```

Based on @Vritra4's suggestion at https://github.com/terra-money/terra.js/pull/295, the app is already using the following packages:

- `@terra-money/terra.js` at `3.0.11`
- `@terra-money/wallet-provider` at `3.8.1`, also tried `3.9.4`

Why is the `CreateTxFailed` error still happening? Is there another combination of package versions I should try if I am using Luna Classic? Or is this a problem with the newer versions of Terra Station?

**Comment by Vritra4** [comment]
wallet-provider 3.9.x or higher won't work with classic network.
could you check network is set to classic on station wallet extension and refresh the page?

**Comment by gameveloster** [comment]
It was a problem with the terra station extension, transactions started posting correctly after making some small changes to the extension to support localterra.

Thanks!
