### ISSUE TITLE
Tx.unpackAny doesn't consider isClassic

### ISSUE THREAD

**Issue by tuloski** [terra-money/terra.js#317]
When using Tx.unpackAny it seems it doesn't consider the isClassic parameter of the LCD.
So for example when unpacking a MsgAggregateExchangeRateVote message with isClassic: true, it trows an error: "Error: Not supported for the network".

**Comment by Vritra4** [comment]
thanks for your report! i’ll be fixed soon. please wait for the new release.

**Comment by tuloski** [comment]
Any tip on how to test a specific commit without waiting for a release? Because when installing with npm to a specific commit instead of a tag it doesn't install the "dist" folder and the package can't be used. Any way to bypass this?
