### ISSUE TITLE
TxApi.decode() has bug.

### ISSUE THREAD

**Issue by comsy-gcp** [terra-money/terra.js#324]
https://github.com/terra-money/terra.js/blob/main/src/client/lcd/api/TxAPI.ts
line 386
decode() function has bug.
Tx.fromBuffer needs "isClassic" for classic terra.

return Tx.fromBuffer(Buffer.from(encodedTx, 'base64'));
fix to
return Tx.fromBuffer(Buffer.from(encodedTx, 'base64'), this.lcd.config.isClassic);

please confirm 
thank you.

**Comment by Vritra4** [comment]
thanks for the report! it'll be fixed.
