### ISSUE TITLE
wasm endpoint

### ISSUE THREAD

**Issue by kailust** [terra-money/terra.js#334]
Hi, what is the url for hitting the query for a contract via http
```
https://pisco-lcd.terra.dev/wasm/contracts/CONTRACT_ADDRESS/store?query_msg=QUERY_MESSAGE
```

Thank you

**Comment by kailust** [comment]
https://pisco-lcd.terra.dev/cosmwasm/wasm/v1/contract/CONTRACT_ADDRESS/smart/base64encodedQUERY_MESSAGE

**Comment by Vritra4** [comment]
like LCDClient.wasm.contractQuery()?
swagger would be helpful for you: https://pisco-lcd.terra.dev/swagger/#/Query/SmartContractState
