### ISSUE TITLE
Following Terra.js Smart Contract section.

### ISSUE THREAD

**Issue by NarcoticNarcoleptic** [terra-money/terra.js#341]
I have copy and pasted the executeMsg section of the smart contract interaction page. I have the schema of the count json "increment" pasted into executeMsg variable. It goes through in the node js repl but gives a message saying rpc error:code = NotFound desc = account terra1qdf.... not found: key not found. But I have the test1 mnemonic pasted into the mk variable and the localterra lcd variable set up correctly. That account it spits out isn't test1. What is going on?

**Comment by NarcoticNarcoleptic** [comment]
import { MsgExecuteContract } from '@terra-money/terra.js';
  import { LCDClient, MsgStoreCode, MnemonicKey, isTxError } from '@terra-money/terra.js';
  
  
  // connect to localterra
  const terra = new LCDClient({
    URL: 'http://localhost:1317',
    chainID: 'localterra'
  });


  const mk = new MnemonicKey({
    mnemonic: 'shiver position copy catalog upset verify cheap library enjoy extend second peasant basic kit polar business document shrug pass chuckle lottery blind ecology stand'
  })
  
  const wallet = terra.wallet(mk);
  const contract_address = 'terra1wpf2szs4uazej8pe7g8vlck34u24cvxx7ys0esfq6tuw8yxygzuqaerxmy';

  const executeMsg = {
    "type": "object",
    "required": [
      "increment"
    ],
    "properties": {
      "increment": {
        "type": "object"
      }
    },
    "additionalProperties": false
  }

const execute = new MsgExecuteContract(
  wallet.key.accAddress, // sender
  contract_address[0], // contract account address
  { ...executeMsg }, // handle msg
  { uluna: 100000 } // coins
);

const executeTx = await wallet.createAndSignTx({
  msgs: [execute]
});

const executeTxResult = await terra.tx.broadcast(executeTx);

console.log(executeTxResult);

---------CONSOLE---------

data: {
      code: 5,
      message: 'rpc error: code = NotFound desc = account terra1qd9fwwgnwmwlu2csv49fgtum3rgms64s8tcavp not found: key not found',
      details: []
    }

**Comment by Vritra4** [comment]
schema is not content of msg. you can call with `{"increment":{}}`. see [this](https://github.com/terra-money/terra.js/blob/168afed3f48cb14607406355d1d62f30411e36a1/integration-tests/contract.ts).
about mnemonic, i think you've pasted incorrectly :) you can use predefined key like the example above.

**Comment by NarcoticNarcoleptic** [comment]
Ah I see! I appreciate the fast reply. May I see an example of using the increment method in Terra.js?

**Comment by Vritra4** [comment]
https://github.com/terra-money/terra.js/blob/168afed3f48cb14607406355d1d62f30411e36a1/integration-tests/contract.ts
this script deploys(with MsgStoreCode and MsgInstantiateContract) a smart contract and call deployed one(with MsgExecuteContract).

**Comment by NarcoticNarcoleptic** [comment]
Thank you so much!

**Comment by NarcoticNarcoleptic** [comment]
I have another quick question for you plz. I mainly want to work with the
NFT standard.
I see that I can send an NFT through Terra station. Does this mean I can
use the json schema that is already generated from the terrain scaffold? Or
would I need to implement the message in the contract enum  first?

**Comment by Vritra4** [comment]
@NarcoticNarcoleptic
this might be helpful for you: https://github.com/CosmWasm/cw-nfts, especially https://github.com/CosmWasm/cw-nfts/tree/main/packages/cw721

schema are not parameters for executing a contract, but descriptions of that parameters.
