### ISSUE TITLE
A lot of broken links 

### ISSUE THREAD

**Issue by FollowMeDown** [terra-money/terra.js#65]
Example : https://terra-project.github.io/terra.js/classes/stakingapi.html

**Comment by hanjukim** [comment]
I can't find page with the link from https://terra-project.github.io/terra.js/ . Would you mind to tell me where it is?

**Comment by FollowMeDown** [comment]
Hello Hanjukim,
i will help you to make this repo clean and find broken links.
Look : 
 - Go to https://github.com/terra-project/terra.js/wiki
 - Menu : Querying

Text : 
```
Each module has its own set of querying functions. You can explore the documentation to get a comprehensive list:

- [ ] auth < Broken Link
- [ ] bank < ...
- [ ] distribution
- [ ] gov
- [ ] market
- [ ] mint
- [ ] msgauth
- [ ] oracle
- [ ] slashing
- [ ] staking
- [ ] supply
- [ ] tendermint
- [ ] treasury
- [ ] tx
- [ ] wasm

```

P.S.
I need you help also ) I am looking info about how can I get full information about my Validator [terra13307pxehvt0qply3kw9vk578u4az0u4mu24yex] from Terra Blockchain with JS Stack. If you provide one Example in WIKI its will be TOP!
BR,
