### ISSUE TITLE
The correct way of forecasting non-luna gas prices

### ISSUE THREAD

**Issue by maayank** [terra-money/terra.js#70]
I see two ways to estimate the gas price for non-luna currencies in the API. For simplicity, let's assume 'ukrw' on testnet:
1. Take the luna gas price from lcd.config.gasPrices (as it's the only entry there) and multiply by the exchange rate for 'ukrw'
2. Build a tx and use or /create /estimate_fee and get the uusd from gasPrices of the fee structure that it returned (here it is filled)

However, I get vastly different values. For ukrw in tequila-4 I get 2986.3737 for (1) and 0.022869 for (2).
Is this the expected behavior?
What is the correct way to estimate the gas price, optimally without creating the transaction beforehand?

**Comment by hanjukim** [comment]
Where did you get uusd gas price for 2?

**Comment by jimryan** [comment]
I'm curious about this too. I see other projects hardcoding gas prices (including terra.js which [hardcodes default uluna gas prices](https://github.com/terra-money/terra.js/blob/b7e7c88/src/client/lcd/LCDClient.ts#L50-L60)). For example, it seems common to hardcode the uusd gas price to 0.15. 

I've been doing something like this with success:
```js
const stdTx = new StdTx([msg], new StdFee(0), [])
const fee = await terraClient.tx.estimateFee(stdTx, { gasPrices: { uusd: 0.15 } });
```

But that's including a hardcoded uusd gas price. That successfully calculates the stability fee and total gas, though, and ultimately works (at least on localterra and tequila), but is that the "correct" way to calculate fees? Is there a better way to estimate the gas price/ask the node for an acceptable gas price?

**Comment by hanjukim** [comment]
@jimryan There are several correct ways to put fees

Given that the recommended gas prices (could be queried from https://fcd.terra.dev/v1/txs/gas_prices) does not change often, I personally prefer to use static `StdFee` when I [create](https://github.com/terra-money/terra.js/blob/9b779092eb3f5565d53d13003795edd4f66af629/src/client/lcd/api/TxAPI.ts#L163) predictable transactions. By the meaning of predictable is the `gas` of the transaction doesn't change much by variables. I prefer this way to minimize network round trips.

In detail, when you see the `create` function without the `fee` parameter it automatically calls `estimateFee` function with default gas prices which doesn't have other gas prices than "uluna" which is not what you probably want.

**Comment by jimryan** [comment]
@hanjukim Thanks! I ended up configuring the client with a hardcoded `uusd` gas price, like this:

```javascript
new LCDClient({
  URL: network.lcdURL,
  chainID: network.chainID,
  gasPrices: network.gasPrices
});
```

Where `network.gasPrices` is: `{ uusd: 0.15 }`.

Then I `estimateFee` manually (so we can perform a balance check and it could be displayed to the user), and then `post` the message and the fee to the Extension.

It sounds like the only way to improve on that would be to query the current `uusd` gas price from the `/gas_prices` endpoint, right?

**Comment by nocmar** [comment]
If I not specify `gasPrices` in LCD client for `uusd` so default for tequila-4 is just `{uluna: 0.15}` I won't get valid fee from `estimateFee` or `create` for  `feeDenoms: ["uusd"]` right?

**Comment by hanjukim** [comment]
Check out #107 I think this will resolve the issue?

**Comment by xcsob** [comment]
> @hanjukim Thanks! I ended up configuring the client with a hardcoded `uusd` gas price, like this:
> 
> ```js
> new LCDClient({
>   URL: network.lcdURL,
>   chainID: network.chainID,
>   gasPrices: network.gasPrices
> });
> ```
> 
> Where `network.gasPrices` is: `{ uusd: 0.15 }`.
> 
> Then I `estimateFee` manually (so we can perform a balance check and it could be displayed to the user), and then `post` the message and the fee to the Extension.
> 
> It sounds like the only way to improve on that would be to query the current `uusd` gas price from the `/gas_prices` endpoint, right?

Can you show me the way you estimate fee? I'm trying with the method, but I'm getting the following error: 
```
Possible Unhandled Promise Rejection (id: 18):
TypeError: Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at TxBody.toProto (/Users/user/Desktop/Project_2/Project/.vscode/.react/index.bundle:270293:33)
    at Tx.toProto (/Users/user/Desktop/Project_2/Project/.vscode/.react/index.bundle:270200:25)
    at Tx.toBytes (/Users/user/Desktop/Project_2/Project/.vscode/.react/index.bundle:270209:109)
    at TxAPI.encode (/Users/user/Desktop/Project_2/Project/.vscode/.react/index.bundle:316578:29)
    at TxAPI.<anonymous> (/Users/user/Desktop/Project_2/Project/.vscode/.react/index.bundle:316544:32)
    at step (/Users/user/Desktop/Project_2/Project/.vscode/.react/index.bundle:316312:21)
    at Object.next (/Users/user/Desktop/Project_2/Project/.vscode/.react/index.bundle:316242:16)
    at /Users/user/Desktop/Project_2/Project/.vscode/.react/index.bundle:316214:69
    at tryCallTwo (/Users/user/Desktop/Project_2/Project/.vscode/.react/index.bundle:31031:7)
    at doResolve (/Users/user/Desktop/Project_2/Project/.vscode/.react/index.bundle:31195:15)
```

The code I'm using: 
```
const signerData = [{sequenceNumber: wallet.key.sequenceNumber,
        publicKey: wallet.key.publicKey}]
        // estimate the fee
        const fee = await this.terra.tx.estimateFee(
            signerData,
            msgs,
            {gasPrices: { uusd: 0.15 }}
        );
```

This is the version of terra.js I have: 
`    "@terra-money/terra.js": "^3.0.0",
`
