### ISSUE TITLE
I believe the length of a terravalconspub should be 82 length, not 83

### ISSUE THREAD

**Issue by petes-fan-club** [terra-money/terra.js#72]
https://github.com/terra-project/terra.js/blob/7bbff355d74e40ff9e558ab7791b5c1c6dfa4640/src/core/strings.ts#L131

for example (from terra.stake.id)
terravalconspub1zcjduepqlnrzpfxsl8vx8mlf9hnjf6y24kczr9ue7k68l82pu23qnjj460ksqy0j0d

**Comment by hanjukim** [comment]
Fixed in #88 and v1.8.2 deployed
