### ISSUE TITLE
extension.isAvailable returns false after refreshing the page

### ISSUE THREAD

**Issue by mbartn** [terra-money/terra.js#74]
I have a `.ts` script on my website. When i call the getters:
```
extension.isAvailable
extension.isAvailable
```
I correctly get values
```
true
true
```
But after refreshing the page I get values
```
false
false
```

I have to hard refresh the page to again get correct values.
I'm using `terra.js 1.6.0`

**Comment by hanjukim** [comment]
What is your environment? It doesn't happen from my end. You actually don't need terra.js library for checking the availablity. Simply open your developer console, and type `window.isTerraExtensionAvailable` to check the value.
