### ISSUE TITLE
Bombay MsgInstantiateContract

### ISSUE THREAD

**Issue by csanti** [terra-money/terra.js#78]
Having trouble instantiating contracts with terra.js on bombay.

I think msg structure for MsgInstantiateContract is not yet updated, should be: https://github.com/terra-money/core/blob/d04903fbcb828f72410e7243f0ac866b42b768fe/x/wasm/types/tx.pb.go#L208

**Comment by hanjukim** [comment]
@csanti I think Yun made some changes into terra.js recently. Could you check this again?
