### ISSUE TITLE
TypeError: Cannot set property 'inpageStream' of undefined

### ISSUE THREAD

**Issue by horodnicdragos** [terra-money/terra.js#82]
There seems to be an issue with the Extension constructor. Reproduced in a fresh create-react-app, see the repo below:

https://github.com/horodnicdragos/terrajs-extension-bug-repro/blob/master/src/App.js

I can't really figure out what is going on.

**Comment by jimryan** [comment]
I just ran into this myself. The docs are wrong. The `Extension` class should be instantiated like any other class: `new Extension()`.
