### ISSUE TITLE
Fix broken wiki links (changes enclosed)

### ISSUE THREAD

**Issue by jimryan** [terra-money/terra.js#85]
There's no good way to open a PR/propose changes to a wiki, so I manually forked the terra.js wiki and committed there. Feel free to pull that down and cherry-pick into your wiki.

Diff: https://github.com/jimryan/terra.js-wiki/compare/master...broken-link-fixes

Commits:
- [8eb42644662c647db09b4275d4fb3a7d149aaacb](https://github.com/jimryan/terra.js-wiki/commit/8eb42644662c647db09b4275d4fb3a7d149aaacb)
- [883bc7cfc6cd2de65b9c1776332b09773f868ab4](https://github.com/jimryan/terra.js-wiki/commit/883bc7cfc6cd2de65b9c1776332b09773f868ab4)

Should fix #65 and #83

**Comment by hanjukim** [comment]
Thank you. It's been updated
