### ISSUE TITLE
[Question] Pagination for Wasm ContractQuery

### ISSUE THREAD

**Issue by Mskalba** [terra-money/terra.js#90]
Hello. I am using:

`terra.wasm.contractQuery(contractAddress, {all_accounts: {limit: LIMIT, start_after: lastAddress}})`

For querying accounts that have particular token. And I have 2 questions regarding it.

1. Pagination. Is there a way to get the full count of addresses or number of pages with given `limit`?

2. If there is no way to get information from point 1. How are new addresses added to that list? As first items or as last items?

**Comment by kjessec** [comment]
1. no
2. generally paginatable address is stored lexicographical order. Having said that, `start_after` usually is whatever that was the last address

also keep in mind that we generally use `30` as hard limit for `limit`
