### ISSUE TITLE
Exception has occurred: TypeError: Cannot set property 'sender' of undefined (Bombay-0007)

### ISSUE THREAD

**Issue by moconno** [terra-money/terra.js#93]
I'm getting the above error when using @terra-money/terra.js@bombay.  It rhows in this method:

function MsgStoreCode(sender, wasm_byte_code) {
        var _this = _super.call(this) || this;
        _this.sender = sender;
        _this.wasm_byte_code = wasm_byte_code;
        return _this;
    }

I'm calling MsgStoreCode like so: 

const storeCode = MsgStoreCode(
    wallet.key.accAddress,
    contract_bytes
)

**Comment by hanjukim** [comment]
`new MsgStoreCode` is proper way to create an object
